//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJY.WebClient.good {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="good.IGood")]
    public interface IGood {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGood/GetGoodName", ReplyAction="http://tempuri.org/IGood/GetGoodNameResponse")]
        string GetGoodName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGood/GetGoodName", ReplyAction="http://tempuri.org/IGood/GetGoodNameResponse")]
        System.Threading.Tasks.Task<string> GetGoodNameAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGoodChannel : JJY.WebClient.good.IGood, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GoodClient : System.ServiceModel.ClientBase<JJY.WebClient.good.IGood>, JJY.WebClient.good.IGood {
        
        public GoodClient() {
        }
        
        public GoodClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GoodClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GoodClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GoodClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetGoodName() {
            return base.Channel.GetGoodName();
        }
        
        public System.Threading.Tasks.Task<string> GetGoodNameAsync() {
            return base.Channel.GetGoodNameAsync();
        }
    }
}
